// sveltekit/src/routes/links/+page.svelte
<div class="flex flex-col justify-center items-center">
  <div class="flex gap-2 mb-2">
    <!-- <app-link-filter (search)="handleSearch($event)">
      <button (click)="toggleDialog()" class="btn btn-primary btn-outline ">Create</button>
    </app-link-filter> -->
  </div>
  <!-- <app-link-list [links]="links()" [search]="search()" (edit)="handleEdit($event)" (delete)="handleDelete($event)" /> -->
</div>

<!-- @if (isOpen()) {
  <app-link-dialog (close)="handleCloseDialog()">
    <app-link-form [link]="selectedLink()" (save)="handleSave($event)" />
  </app-link-dialog>
} -->

// src/app/pages/links/links.component.ts
import { Component, Signal, inject } from '@angular/core';
import { LinksService } from '../../services/links.service';
import { CommonModule } from '@angular/common';
import { toSignal } from '@angular/core/rxjs-interop';
import { Link } from '../../interfaces/Link';
import { LinkListComponent } from '../../features/links/link-list/link-list.component';

@Component({
  selector: 'app-links',
  standalone: true,
  imports: [
    CommonModule,
    LinkListComponent
  ],
  templateUrl: './links.component.html',
  styleUrl: './links.component.scss'
})
export class LinksComponent {
  #linksService = inject(LinksService);

  links: Signal<Link[]>;

  constructor() {
    this.links = toSignal(this.#linksService.getAll(), { initialValue: [] });
   }

   handleEdit(link: Link) {
    console.log('edit', link)
   }

   handleDelete(id: number) {
    console.log('delete', id)
   }
}

<div class="flex flex-col justify-center items-center">
  <div class="flex gap-2 mb-2">
    <app-link-filter (search)="handleSearch($event)">
      <button (click)="toggleDialog()" class="btn btn-primary btn-outline ">Create</button>
    </app-link-filter>
  </div>
  <!-- <app-link-list [links]="links()" [search]="search()" (edit)="handleEdit($event)" (delete)="handleDelete($event)" /> -->
</div>


<app-link-categories [categories]="categories()" />

@if (isOpen()) {
  <app-link-dialog (close)="handleCloseDialog()">
    <app-link-form [link]="selectedLink()" (save)="handleSave($event)" />
  </app-link-dialog>
}
