// angular/src/app/pages/links/links.component.ts
import { Component, Signal, computed, effect, inject, input, signal } from '@angular/core';
import { LinksService } from '../../services/links.service';
import { CommonModule } from '@angular/common';
import { takeUntilDestroyed, toSignal } from '@angular/core/rxjs-interop';
import { Link, LinkCategoryFull } from '../../interfaces/Link';
import { LinkListComponent } from '../../features/links/link-list/link-list.component';
import { LinkFilterComponent } from '../../features/links/link-filter/link-filter.component';
import { LinkDialogComponent } from '../../features/links/link-dialog/link-dialog.component';
import { LinkFormComponent } from '../../features/links/link-form/link-form.component';
import { LinkForm } from '../../models/Link';
import { ActivatedRoute, Router, RouterModule } from '@angular/router';
import { LinkCategoriesComponent } from '../../features/links/link-categories/link-categories.component';
import { map, tap } from 'rxjs';

@Component({
  selector: 'app-links',
  standalone: true,
  imports: [
    CommonModule,
    LinkListComponent,
    LinkFilterComponent,
    LinkDialogComponent,
    LinkFormComponent,
    LinkCategoriesComponent,
    RouterModule
  ],
  templateUrl: './links.component.html',
  styleUrl: './links.component.scss'
})
export class LinksComponent {
  #router = inject(Router);
  #activatedRoute = inject(ActivatedRoute);
  #linksService = inject(LinksService)
  idParam: Signal<string | undefined>
  links = input<Link[]>([]);
  categories = input<LinkCategoryFull[]>([]);
  selectedLink = signal<Link | undefined>(undefined);
  isOpen = signal(false);
  search = signal('');

  constructor() {
    this.idParam = toSignal(this.#activatedRoute.queryParams.pipe(
      map(params => params['category'])
    ));
  }

  handleEdit(link: Link) {
    this.isOpen.set(true);
    this.selectedLink.set(link);
  }

  handleDelete(id: number) {
    this.#linksService.delete(id).subscribe(() => this.reload());
  }
  handleSave(linkForm: LinkForm) {
    this.resetDialog();
    this.#linksService.createOrUpdate(linkForm, this.idParam()).subscribe(() => this.reload());
  }

  handleCloseDialog() {
    this.resetDialog();
  }


  handleSearch(value: string) {
    this.search.set(value)
  }

  toggleDialog() {
    this.isOpen.update(x => !x);
  }

  private resetDialog() {
    this.isOpen.set(false);
    this.selectedLink.set(undefined);
  }

  private reload() {
    const { pathname, search } = window.location;
    const currentUrl = `${pathname}${search}`;
    this.#router.navigateByUrl(currentUrl)
  }
}

<div class="flex flex-col justify-center items-center">
  <div class="flex gap-2 mb-2">
    <app-link-filter (search)="handleSearch($event)">
      <button (click)="toggleDialog()" class="btn btn-primary btn-outline ">Create</button>
    </app-link-filter>
  </div>
  @if(isLoading()) {
    <span class="loading loading-ring loading-lg"></span>
  } @else {
    <app-link-list [links]="links()" [search]="search()" (edit)="handleEdit($event)" (delete)="handleDelete($event)" />
  }
</div>


<app-link-categories [categories]="categories()" />

@if (isOpen()) {
  <app-link-dialog (close)="handleCloseDialog()">
    <app-link-form [link]="selectedLink()" (save)="handleSave($event)" />
  </app-link-dialog>
}

// sveltekit/src/routes/links/+page.svelte
<script lang="ts">
  import Dialog from "$lib/features/links/Dialog.svelte";
  import Filter from "$lib/features/links/Filter.svelte";
  import Links from "$lib/features/links/Links.svelte";
  import type { Link } from "$lib/interfaces/Link";
  import type { PageServerLoad } from "./$types";

  const { data } = $props<{data: PageServerLoad}>();
  let search = $state('');

  function handleSearch(value: string) {
    search = value;
  }
</script>

<div class="flex flex-col justify-center items-center">
  <div class="flex gap-2 mb-2">
    <Filter search={handleSearch}>
      <button class="btn btn-primary btn-outline">Create</button>
    </Filter>
  </div>
  <Links search={search} links={data.links} />
  <!-- <app-link-list [links]="links()" [search]="search()" (edit)="handleEdit($event)" (delete)="handleDelete($event)" /> -->
</div>

<Dialog />
<!-- @if (isOpen()) {
  <app-link-dialog (close)="handleCloseDialog()">
    <app-link-form [link]="selectedLink()" (save)="handleSave($event)" />
  </app-link-dialog>
} -->
